import { useEffect, useState } from 'react';
import { ApiError } from '../../shared/api/apiClient';
import { StatusMessage } from '../../shared/ui/StatusMessage';
import { createMedicine, deleteMedicine, listMedicines } from './api';
import { MedicineForm } from './MedicineForm';
import { MedicineList } from './MedicineList';
import type { Medicine, MedicinePayload } from './types';

export function MedicineReminderModule() {
  const [medicines, setMedicines] = useState<Medicine[]>([]);
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  const [message, setMessage] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [deletingId, setDeletingId] = useState<number | null>(null);

  useEffect(() => {
    void loadMedicines();
  }, []);

  async function loadMedicines() {
    setStatus('loading');
    setMessage('');
    try {
      setMedicines(await listMedicines());
      setStatus('ready');
    } catch (error) {
      setStatus('error');
      setMessage(error instanceof ApiError ? error.message : 'Unable to load medicines.');
    }
  }

  async function handleCreate(payload: MedicinePayload) {
    setIsSaving(true);
    setMessage('');
    try {
      const created = await createMedicine(payload);
      setMedicines((current) => [created, ...current]);
      setMessage('Medicine saved and reminders are ready to be generated by the backend.');
    } catch (error) {
      setMessage(error instanceof ApiError ? error.message : 'Unable to save medicine.');
    } finally {
      setIsSaving(false);
    }
  }

  async function handleDelete(id: number) {
    setDeletingId(id);
    setMessage('');
    try {
      await deleteMedicine(id);
      setMedicines((current) => current.filter((medicine) => medicine.id !== id));
      setMessage('Medicine archived.');
    } catch (error) {
      setMessage(error instanceof ApiError ? error.message : 'Unable to archive medicine.');
    } finally {
      setDeletingId(null);
    }
  }

  return (
    <section className="feature-section" aria-labelledby="medicine-title">
      <div className="section-heading">
        <div>
          <p className="eyebrow">Add Medicine</p>
          <h2 id="medicine-title">Create medicine reminders</h2>
        </div>
      </div>

      {message && <StatusMessage tone={message.toLowerCase().includes('unable') ? 'error' : 'success'}>{message}</StatusMessage>}

      <MedicineForm isSaving={isSaving} onSubmit={handleCreate} />

      <div className="subsection-heading">
        <h3>Existing medicines</h3>
        <button className="ghost-button" type="button" onClick={loadMedicines}>
          Refresh
        </button>
      </div>

      {status === 'loading' && <StatusMessage>Loading medicines...</StatusMessage>}
      {status === 'error' && <StatusMessage tone="error">{message || 'Unable to load medicines.'}</StatusMessage>}
      {status === 'ready' && <MedicineList medicines={medicines} isDeletingId={deletingId} onDelete={handleDelete} />}
    </section>
  );
}
