import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";

import { ApiError } from "../../lib/api";
import { ReportsPage } from "./ReportsPage";

const listMock = vi.fn();
const uploadMock = vi.fn();
const analyzeMock = vi.fn();
const getAnalysisMock = vi.fn();

vi.mock("../../lib/api", async () => {
  const actual = await vi.importActual<typeof import("../../lib/api")>("../../lib/api");

  return {
    ...actual,
    reportsApi: {
      list: (...args: unknown[]) => listMock(...args),
      upload: (...args: unknown[]) => uploadMock(...args),
      analyze: (...args: unknown[]) => analyzeMock(...args),
      getAnalysis: (...args: unknown[]) => getAnalysisMock(...args)
    }
  };
});

describe("ReportsPage", () => {
  beforeEach(() => {
    listMock.mockReset();
    uploadMock.mockReset();
    analyzeMock.mockReset();
    getAnalysisMock.mockReset();
  });

  it("shows loading and then an empty state when there are no reports", async () => {
    listMock.mockResolvedValueOnce([]);

    render(<ReportsPage />);

    expect(screen.getByText("Loading reports...")).toBeInTheDocument();
    expect(await screen.findByText("No reports uploaded")).toBeInTheDocument();
  });

  it("shows a retryable error when loading reports fails", async () => {
    listMock
      .mockRejectedValueOnce(new Error("Unable to load reports."))
      .mockResolvedValueOnce([]);

    const user = userEvent.setup();

    render(<ReportsPage />);

    expect(await screen.findByText("Unable to load reports.")).toBeInTheDocument();

    await user.click(screen.getByRole("button", { name: "Retry" }));

    expect(await screen.findByText("No reports uploaded")).toBeInTheDocument();
  });

  it("uploads and analyzes a report successfully", async () => {
    const user = userEvent.setup();

    listMock
      .mockResolvedValueOnce([])
      .mockResolvedValueOnce([
        {
          id: 7,
          originalFilename: "blood-report.pdf",
          mimeType: "application/pdf",
          fileSize: 2048,
          analysisStatus: "uploaded",
          createdAt: "2026-04-21T00:00:00.000Z"
        }
      ])
      .mockResolvedValueOnce([
        {
          id: 7,
          originalFilename: "blood-report.pdf",
          mimeType: "application/pdf",
          fileSize: 2048,
          analysisStatus: "completed",
          createdAt: "2026-04-21T00:00:00.000Z"
        }
      ]);
    uploadMock.mockResolvedValueOnce({
      id: 7,
      originalFilename: "blood-report.pdf"
    });
    getAnalysisMock.mockRejectedValue(new ApiError("Analysis missing.", 404, "NOT_FOUND"));
    analyzeMock.mockResolvedValueOnce({
      analysis: {
        reportId: 7,
        summaryLayman: "This report was summarized for quick review.",
        risks: ["Blood sugar markers may be above the expected range."],
        medicineSuggestions: ["Discuss medicine changes with a clinician."],
        vitaminSuggestions: ["Ask whether vitamin review is needed."],
        importantNotes: ["Do not change medicines without clinician guidance."],
        disclaimer: "This analysis is informational only and not a diagnosis.",
        aiModel: "gpt-5.4-mini",
        createdAt: "2026-04-21T00:00:00.000Z"
      }
    });

    render(<ReportsPage />);

    expect(await screen.findByText("No reports uploaded")).toBeInTheDocument();

    const input = screen.getByLabelText("Upload report file") as HTMLInputElement;
    const file = new File(["mock"], "blood-report.pdf", { type: "application/pdf" });
    fireEvent.change(input, {
      target: { files: [file] }
    });

    expect(await screen.findByText("Uploaded blood-report.pdf.")).toBeInTheDocument();
    expect(await screen.findByText("No analysis yet")).toBeInTheDocument();

    await user.click(screen.getByRole("button", { name: "Run Analysis" }));

    await waitFor(() => {
      expect(analyzeMock).toHaveBeenCalledWith(7);
    });

    expect(await screen.findByText("Analysis completed successfully.")).toBeInTheDocument();
    expect(await screen.findByText("This report was summarized for quick review.")).toBeInTheDocument();
    expect(screen.getByText("This analysis is informational only and not a diagnosis.")).toBeInTheDocument();
    expect(screen.getByText("Generated by gpt-5.4-mini")).toBeInTheDocument();
    expect(screen.getByText("completed")).toBeInTheDocument();
  });

  it("renders an existing saved analysis when a completed report is selected", async () => {
    listMock.mockResolvedValueOnce([
      {
        id: 4,
        originalFilename: "lab-summary.pdf",
        mimeType: "application/pdf",
        fileSize: 1024,
        analysisStatus: "completed",
        createdAt: "2026-04-21T00:00:00.000Z"
      }
    ]);
    getAnalysisMock.mockResolvedValueOnce({
      reportId: 4,
      summaryLayman: "Stored analysis summary from the backend.",
      risks: ["Review the cholesterol trend with your clinician."],
      medicineSuggestions: ["Discuss whether medicine timing needs review."],
      vitaminSuggestions: ["Ask if vitamin follow-up is needed."],
      importantNotes: ["Keep the original report handy for your visit."],
      disclaimer: "This analysis is informational only and not a diagnosis.",
      aiModel: "gpt-5.4-mini",
      createdAt: "2026-04-21T00:00:00.000Z"
    });

    render(<ReportsPage />);

    expect(await screen.findByText("Loading saved analysis")).toBeInTheDocument();
    expect(await screen.findByText("Stored analysis summary from the backend.")).toBeInTheDocument();
    expect(screen.getByText("Generated by gpt-5.4-mini")).toBeInTheDocument();
    expect(screen.getByText("Review the cholesterol trend with your clinician.")).toBeInTheDocument();
  });

  it("shows an explicit analysis fetch error for non-404 failures", async () => {
    listMock.mockResolvedValueOnce([
      {
        id: 9,
        originalFilename: "scan.png",
        mimeType: "image/png",
        fileSize: 2048,
        analysisStatus: "failed",
        createdAt: "2026-04-21T00:00:00.000Z"
      }
    ]);
    getAnalysisMock.mockRejectedValueOnce(new Error("Saved analysis could not be loaded."));

    render(<ReportsPage />);

    expect(await screen.findByText("Analysis unavailable")).toBeInTheDocument();
    expect(screen.getByText("Saved analysis could not be loaded.")).toBeInTheDocument();
  });

  it("shows a waiting state for reports that are still processing", async () => {
    listMock.mockResolvedValueOnce([
      {
        id: 11,
        originalFilename: "pending-report.pdf",
        mimeType: "application/pdf",
        fileSize: 3072,
        analysisStatus: "processing",
        createdAt: "2026-04-21T00:00:00.000Z"
      }
    ]);
    getAnalysisMock.mockRejectedValueOnce(new ApiError("Analysis missing.", 404, "NOT_FOUND"));

    render(<ReportsPage />);

    expect(await screen.findByText("Analysis in progress")).toBeInTheDocument();
  });
});
